name: habit
dependencies:
- flask=0.10.1=py35_1
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- openssl=1.0.2h=0
- pip=8.1.1=py35_1
- python=3.5.1=0
- readline=6.2=2
- setuptools=20.7.0=py35_0
- sqlite=3.11.1=0
- tk=8.5.18=0
- werkzeug=0.11.9=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0

