name: habit
dependencies:
- anaconda-client=1.4.0=py35_0
- clyent=1.2.2=py35_0
- flask=0.10.1=py35_1
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- openssl=1.0.2h=0
- pip=8.1.1=py35_1
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=20.7.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.11.1=0
- tk=8.5.18=0
- werkzeug=0.11.9=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - arrow==0.7.0
  - binaryornot==0.4.0
  - chardet==2.3.0
  - click==6.6
  - cookiecutter==1.4.0
  - future==0.15.2
  - jinja2-time==0.1.0
  - poyo==0.2.0
  - tinydb==3.2.0
  - whichcraft==0.4.0

